version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=jisub
      - MONGO_PASSWORD=helloworld
      - SESSION_SECRET=secret

    command: npm run dev
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jisub
      - MONGO_INITDB_ROOT_PASSWORD=helloworld
